<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught ArgumentCountError: defined() expects exactly 1 argument, 2 given in /var/www/html/mitarbeiter/plugins/editors/jckeditor/includes.php on line <i>47</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> ArgumentCountError: defined() expects exactly 1 argument, 2 given in /var/www/html/mitarbeiter/plugins/editors/jckeditor/includes.php on line <i>47</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>380592</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/html/mitarbeiter/plugins/editors/jckeditor/typography/typography2.php' bgcolor='#eeeeec'>.../typography2.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>405616</td><td bgcolor='#eeeeec'>require( <font color='#00bb00'>'/var/www/html/mitarbeiter/plugins/editors/jckeditor/includes.php</font> )</td><td title='/var/www/html/mitarbeiter/plugins/editors/jckeditor/typography/typography2.php' bgcolor='#eeeeec'>.../typography2.php<b>:</b>12</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>407656</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.defined' target='_new'>defined</a>( <span>$constant_name = </span><span>&#39;_JREQUEST_NO_CLEAN&#39;</span>, <span>1</span> )</td><td title='/var/www/html/mitarbeiter/plugins/editors/jckeditor/includes.php' bgcolor='#eeeeec'>.../includes.php<b>:</b>47</td></tr>
</table></font>
